baseURL: https://iehow.tw/ # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: 
paginate: 5
theme: charlolamode

menu:
    main:
        - name: Bio
          url: /bio/
          weight: 30
        - name: Articles
          url: /articles/
          weight: 20
        - name: Projects
          url: /projects/
          weight: 15


params:
    author: 
    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    displayFullLangName: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true

    profileMode:
        # Disable to populate home page with 'mainSections' content
        enabled: true
        title: Howie
        description: |

          Hello, I'm a Computer Science student from Taiwan.

          Also a Minecraft Server owner.
        imageUrl: "/images/profile.webp"
        imageTitle: avator
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Don't click me 🤭
              url: https://www.youtube.com/watch?v=dQw4w9WgXcQ

    mainSections:
      - articles

    socialIcons:
        - name: buymeacoffee
          url: "https://ko-fi.com/Howie0715"
        - name: github
          url: "https://github.com/Howie0715"
        - name: email
          url: "mailto:howie0715@gmail.com"
        - name: twitter
          url: "https://twitter.com/Howie_0715"
        - name: youtube
          url: "https://www.youtube.com/@howie0715"

    # change favicon in images folder (icon for web tab)
    assets:
          favicon: "/images/icon.png"

enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true

